### ISSUE TITLE
GO CRAZY - return value of a process

### ISSUE THREAD

**Issue by carlosrocha-dev** [tonnytg/42_minishell#150]
## Test:
'''BASH
true;
result1=$?;
false;
result2=$?;
sum=$((result1 + result2));
echo "-> $sum"
echo ----------
true;
result1=$?;
true;
result2=$?;
sum=$((result1 + result2));
echo "-> $sum"
'''

## result

![Captura de Tela 2023-08-09 às 02 07 19](https://github.com/tonnytg/42_minishell/assets/3737837/f3b741ab-1efb-41a7-9bd8-369e85783d81)

**Comment by carlosrocha-dev** [comment]
@tonnytg i`m not sure if this is valid but this test the echo command don`t pass.

**Comment by tonnytg** [comment]
This need review this topic and understand this is a bug or not
