### ISSUE TITLE
Double less append double less

### ISSUE THREAD

**Issue by tonnytg** [tonnytg/42_minishell#175]
Must be equal a bash
`cat file.txt > file.txt`

**Comment by carlosrocha-dev** [comment]
No workspace parece identico
![image](https://github.com/tonnytg/42_minishell/assets/3737837/7a73260e-aa05-4d30-b7d5-e30d97c11fb4)

---

![image](https://github.com/tonnytg/42_minishell/assets/3737837/1053cb14-b153-41b4-83ad-11bd5471542f)
