### ISSUE TITLE
export with no options

### ISSUE THREAD

**Issue by tonnytg** [tonnytg/42_minishell#19]
Ref: https://www.computerhope.com/unix/bash/export.htm

*Definition of done*:

The shell shall format the output, including the proper use of quoting, so that it is suitable for reinput to the shell
       as commands that achieve the same exporting results, except:

        1. Read-only variables with values cannot be reset.

        2. Variables that were unset at the time they were output need not be reset to the unset state if a value is  assigned
           to  the  variable  between  the  time  the state was saved and the time at which the saved output is reinput to the
           shell.

       When no arguments are given, the results are unspecified. If a variable assignment precedes the command name of  export
       but that variable is not also listed as an operand of export, then that variable shall be set in the current shell exe‐
       cution environment after the completion of the export command, but it is unspecified whether that  variable  is  marked
       for export.

**Comment by carlosrocha-dev** [comment]
@tonnytg as `set_command` has some commands defined to work, generalization of the function is necessary. This will help us in coding productivity. Is that ok with you?
