### ISSUE TITLE
bug: awk doesn`t work

### ISSUE THREAD

**Issue by carlosrocha-dev** [tonnytg/42_minishell#216]
command: echo -e "Um\tDois\tTrês\nQuatro\tCinco\tSeis" | awk '{print $1}'
<img width="617" alt="image" src="https://github.com/tonnytg/42_minishell/assets/3737837/93f92e40-adcb-4f3f-88be-f08d0413b759">

**Comment by tonnytg** [comment]
@carlosrocha-dev can you review this bug, `echo -e` it not in PDF rules`
