### ISSUE TITLE
exit with no options

### ISSUE THREAD

**Issue by tonnytg** [tonnytg/42_minishell#22]
**Commands need return:**

- [x] **CMD:** exit 1 2 3

**Must return:** bash: exit: too many arguments
**ERROR CODE:** 127 or 1 ? Need check

- [x] **CMD:** exit a

**Must return:** bash: exit: a: numeric argument required
**ERROR CODE:** 2

- [x] **CMD:** exit 8

**Must return:** exit
**ERROR CODE:** 8

- [x] **CMD:** exit -2

**Must return:** exit
**ERROR CODE:** 254
**NOTE:** Mod of 255 to return 254 just like bash

**Docs:**
https://www.linuxdoc.org/LDP/abs/html/exitcodes.html

**Comment by carlosrocha-dev** [comment]
Referência para o comando exit e o tratamento dos "FDs":
https://www.gnu.org/software/bash/manual/bash.html#Exit-Status

comecei uma implementação mas falta validar.
