### ISSUE TITLE
bug: remove prohibited functions 

### ISSUE THREAD

**Issue by tonnytg** [tonnytg/42_minishell#224]

**Comment by tonnytg** [comment]
https://github.com/tonnytg/42_minishell/blob/15ef510a7f25ac3c22c26b1665919c9c05739d29/srcs/commands/here_doc.c#L68

**Comment by carlosrocha-dev** [comment]
![Captura de Tela 2023-08-19 às 21 34 32](https://github.com/tonnytg/42_minishell/assets/3737837/9676598c-abf9-4eb6-921a-a76c2bfb6942)
