### ISSUE TITLE
bug: sigle quotes can't interpret envs

### ISSUE THREAD

**Issue by carlosrocha-dev** [tonnytg/42_minishell#228]
![image](https://github.com/tonnytg/42_minishell/assets/3737837/04453d31-661f-4daa-8f09-8d13d5c94ada)

**Comment by tonnytg** [comment]
![Screenshot 2023-08-20 at 17 54 40](https://github.com/tonnytg/42_minishell/assets/1833882/a8d5243a-00d5-4ebf-b9fa-fe61bc84d910)

Já estava funcionando, faltou apenas teste do nosso lado.

**Comment by tonnytg** [comment]
Foi identificado que o 'ola mundo $PWD' estava acionando o gatilho cmds->d_parse para 1 mas não estava voltando, causando que todos os próximso comandos não fosse interpretado.
