### ISSUE TITLE
av1: export improve declare

### ISSUE THREAD

**Issue by tonnytg** [tonnytg/42_minishell#229]
![Screenshot 2023-08-20 at 09 59 25](https://github.com/tonnytg/42_minishell/assets/1833882/dd12b4bb-e1d7-4d8d-bfcd-a54602b8a7db)

**Comment by tonnytg** [comment]
![Screenshot 2023-08-20 at 09 59 56](https://github.com/tonnytg/42_minishell/assets/1833882/120932cb-3dc1-4bea-853d-97fcb91bb2fd)

**Comment by carlosrocha-dev** [comment]
![image](https://github.com/tonnytg/42_minishell/assets/3737837/b2b7acad-7c93-4a5b-a060-0997b55c643e)

**Comment by tonnytg** [comment]
![Screenshot 2023-08-20 at 10 02 42](https://github.com/tonnytg/42_minishell/assets/1833882/d79128e5-6aba-4605-9394-61a091582069)

**Comment by carlosrocha-dev** [comment]
![image](https://github.com/tonnytg/42_minishell/assets/3737837/83730243-f72c-4c2b-98ad-938494583b9e)

**Comment by tonnytg** [comment]
com ou sem igual
![Screenshot 2023-08-20 at 10 03 35](https://github.com/tonnytg/42_minishell/assets/1833882/df4188f6-3f63-40c5-9716-c7e1910ddbcc)

**Comment by carlosrocha-dev** [comment]
![image](https://github.com/tonnytg/42_minishell/assets/3737837/875b946c-f57b-43d0-a79f-389a2461dfa9)
