### ISSUE TITLE
av1: cd

### ISSUE THREAD

**Issue by tonnytg** [tonnytg/42_minishell#230]

**Comment by tonnytg** [comment]
![Screenshot 2023-08-20 at 10 07 00](https://github.com/tonnytg/42_minishell/assets/1833882/4c71dafc-a7b3-4654-98af-109d0c5d7b0e)

**Comment by carlosrocha-dev** [comment]
![image](https://github.com/tonnytg/42_minishell/assets/3737837/ad37d184-15f8-4208-b7ee-d4b44efaab47)
